apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: api-pagos
  title: API de Pagos
  description: API para procesar pagos en la Aplicación A190
  tags:
    - aplicacion-a190  # Relacionar con A190 sin necesidad de providesApis
spec:
  type: openapi
  lifecycle: production
  owner: equipo-finanzas
  definition:
    $text: https://raw.githubusercontent.com/RafaelReynoso/Lab13-AplicacionesEmpresarialesAvanzadas/refs/heads/master/openapi.yaml
